export { Cart } from './cart/cart.component'
export { Header } from './header/header.component'
export { Modal } from './modal/modal.component'
export { Pagination } from './pagination/pagination.component'
export { PokemonCard } from './pokemon-card/pokemon-card.component'
export { SearchBar } from './search-bar/search-bar.component'
